movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/',views.home,name='home'),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path('add/', views.add_movie, name='add_movie'),
    path('add/home/',views.home,name='home'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('search/', views.search, name='search'),
    path('all_movie_cat/', views.category, name='category'),
    path('<slug:c_slug>/', views.category , name='category'),
    path('movie/<int:movie_id>/post_review',views.post_review,name='post_review'),
    path('movie/<int:movie_id>/post_rating', views.post_rating, name='post_rating'),


]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('',include('users.urls')),
	path('', include('django.contrib.auth.urls')),
	path('',include('movieapp.urls')),

]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/users/urls.py
from django.urls import path
from . import views
app_name='users'

urlpatterns=[
    path('register', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('profile/',views.view_profile,name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/edit/view_profile/', views.view_profile, name='view_profile'),
    path('logout', views.logout, name='logout'),
]

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="container my_div">
    <h1>Add New Movie</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" id="name" name="name" placeholder="Enter the Movie name" required><br>
        <input type="text" id="desc" name="desc" rows="4" cols="50" placeholder="Enter the description here" required></input><br>
        <input type="text" id="actors" name="actors" placeholder="Enter the Name of Actors here" required><br>
        <label for="trailer_link" style="margin-left:40%">Trailer Link:</label>
        <input type="url" id="trailer_link" name="trailer_link" placeholder="Copy the tailer here"><br><br>
        <label for="release" style="margin-left:40%">Release Date:</label>
        <input type="date" id="release" name="release" required> <br><br>
        <label for="img" style="margin-left:40%">Image:</label>
        <input type="file" id="img" name="img" accept="image/*" required> <br><br>
        <select name="category" id="category" style="margin-left:40%">
            {% for cat in links %}
            <option value="{{cat.category_name}}">{{cat.category_name}}</option>
            {% endfor %}
        </select><br> <br>
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>movies</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>

    <!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<div class="Container">
    <div>
        {% include 'nav.html' %}
        {% block body %}
        {% endblock %}
    </div>
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/mixitup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</div>
 </body>
</html>

movieproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>{{ category.name }} Movies</h1>
            <p>{{ category.description }}</p>
        </div>
    </div>
    <div class="row">
        {% for movie in movies %}
        <div class="col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{ movie.img.url }}" alt="Card image cap" height="250px">
                <div class="card-body">
                    <h5 class="card-title">{{ movie.name }}</h5>
                    <p class="card-text">{{ movie.desc }}</p>
                    <a href="{% url 'movieapp:details' movie.id %}" class="btn btn-primary">View Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

movieproject/templates/delete.html
<form method="POST">
    {%  csrf_token %}
    Do you want to delete ths movie?
    <input type="submit">
</form><form method="POST">
    {%  csrf_token %}
    Do you want to delete ths movie?
    <input type="submit">
</form>

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ movie.img.url }}" width="150" height="150">
        </div>
        <div class="col-md-6">
            <h3>{{ movie.name }}</h3>
            <h5>Description: {{ movie.desc }}</h5>
            <h5>Released on: {{ movie.release }}</h5>
            <h5>Actors: {{ movie.actors }}</h5>
            <h5>Category: {{ movie.category }}</h5>
            {% if movie.trailer_link %}
                <a href="{{ movie.trailer_link }}">Watch Trailer</a>
            {% else %}
                <p>No trailer available</p>
            {% endif %}
            <br>
            {% if user == movie.added_by %}
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">UPDATE</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">DELETE</a>
            {% endif %}
            <a class="btn btn-info" href="{% url 'movieapp:post_review' movie.id %}">Review and Rate</a>
        </div>
    </div>
</div>

<hr>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Movie Ratings</h2>
            <ul>
                {% for rating in ratings %}
                    <li>{{ rating.user.username }}: {{ rating.rating_value }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-6">
            <h2>Movie Reviews</h2>
            <ul>
                {% for review in reviews %}
                    <li>{{ review.user.username }}: {{ review.review_text }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row mx_auto">
        {% for movie in page_obj %}
            <div class="col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ movie.img.url }}" alt="Card image cap" height="250px">
                    <div class="card-body">
                        <h5 class="card-title">{{ movie.name }}</h5>
                        <p class="card-text">{{ movie.desc }}</p>
                        <a href="{% url 'movieapp:details' movie.id %}" class="btn btn-primary">View Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if page_obj.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
                {% for pg in page_obj.paginator.page_range %}
                    <a href="?page={{ pg }}" class="btn btn-light bt-sm {% if page_obj.number == pg %} active {% endif %}">{{ pg }}</a>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

	<section class="hero-section">
		<div class="hero-slider owl-carousel">
			<div class="hs-item">
				<div class="container">
					<div class="row">
						<div class="col-lg-6">
							<div class="hs-text">
								<h2><span>Movie</span> for everyone.</h2>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. </p>
								<a href="{% url 'users:login' %}" class="site-btn">Login</a>
								<a href="{% url 'users:register' %}" class="site-btn sb-c2">Register</a>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="hr-img">
								<img src="{% static 'img/hero-bg.png' %}" alt="image">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="hs-item">
				<div class="container">
					<div class="row">
						<div class="col-lg-6">
							<div class="hs-text">
								<h2><span>Watch your</span> Favourite Movie Details.</h2>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. </p>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="hr-img">
								<img src="{% static 'img/mv.jpeg' %}" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

movieproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">MOVIE STORE</a>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movieapp:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movieapp:add_movie' %}">Add Movie</a>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:view_profile' %}">Profile</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          CATEGORIES
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.category_name}} </a>
          {% endfor %}
        </div>
      </li>
      <form class="d-flex" action="{% url 'movieapp:search' %}" method="get" role="search">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i>Search</button>
      </form>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'users:login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
    
  </div>
</nav>

movieproject/templates/post_review.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h1>Review</h1>
<div class="log_body">
    <form action="post_review" method="post">
        {% csrf_token %}
        <input type="text" name="review_text" placeholder="Enter your review" width="50" height="20"><br>
        <input type="submit"><br>
    </form>
</div>
<h1>Rating</h1>
<div class="log_body">
    <form action="post_rating" method="post">
        {% csrf_token %}
        <label for="rating_value">Rating Value:</label>
        <input type="number" id="rating_value" name="rating_value" placeholder="Enter your rating value" min="1" max="5"><br>
        <button type="submit">Submit Rating</button>
    </form>
</div>
{% endblock %}

movieproject/templates/profile.html
{% extends 'base.html' %}
{% block title %} Profile Page {% endblock %}
{% block body %}

<h1>Edit your Profile, {{user.username}}</h1>
<div class="form-content">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
            {{ form.as_p }}
                <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
                <button type="reset" class="btn btn-dark btn-lg">Reset</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

movieproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h1>REGISTRATION</h1>
<div class="container reg_body">
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your Username" required><br>
    <input type="text" name="first_name" placeholder="Enter your First name" required><br>
    <input type="text" name="last_name" placeholder="Enter your Last name" required><br>
    <input type="email" name="email" placeholder="Enter your Email id" required><br>
    <input type="password" name="password" placeholder="Enter your Password" required><br>
    <input type="password" name="password1" placeholder="Confirm Your Password" required><br>
    <input type="submit">
</form>
</div>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
{% endblock %}

movieproject/templates/searchresults.html
<!-- search.html -->
{% extends 'base.html' %}
{% block title %}
Search
{% endblock %}
{% block body %}
<div class="container">
<h1>Search Results</h1> <br>
    <div class="row mx_auto">
        {% for movie in movies %}
        <div class="col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{ movie.img.url }}" alt="Card image cap" height="250px">
                <div class="card-body">
                    <h5 class="card-title">{{ movie.name }}</h5>
                    <p class="card-text">{{ movie.desc }}</p>
                    <a href="{% url 'movieapp:details' movie.id %}" class="btn btn-primary">View Details</a>
                </div>
            </div>
        </div>
        {% empty %}
        <h3> No movie found </h3>
        {% endfor %}
    </div>
</div>
{% endblock %}

movieproject/templates/view_profile.html
{% extends 'base.html' %}
{% block title %} Profile Page {% endblock title %}

{% block body %}
<h1>This is the profile page for {{user.username}}</h1><br>
<div class="form-content">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <div class="card" style="width: 30rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Name: {{user.username}}</h5>
                                <p class="card-text">Email: {{ user.email }}</p>
                                <p class="card-text">Bio: {{ profile.bio }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div>
    <button type="button" class=""btn btn-info">
    <a href="{% url 'users:edit_profile' %}"> If you want to edit your profile,CLICK HERE </a>
    </button>
</div>
{% endblock %}